### PR TITLE
add end to the pot to prevent drips after global settlement starts

### PR DESCRIPTION
**Pull request by iamchrissmith**
Add Cage to the Pot so that when we start the `End` `Pot.drip` will no longer accumulate `DAI`

### CODE REVIEW

**Review by gbalabasquer — APPROVED** [review]
LGTM

**Comment by kmbarry1** [comment]
LGTM. I guess we should update the spec for `Pot.drip` in k-dss too.

**Comment by kmbarry1** [comment]
I rather like Lev's point about setting `dsr = RAY` (might break a bunch of dapps and even prevent Dai redemption)...although this also requires adding a `live` check to `file` so that malicious governance is prevented from changing the DSR value post-`cage`.

**Comment by gbalabasquer** [comment]
@kmbarry1 malicious governance can replace directly the `pot` contract by a new one, excepting we put the `require(live == 1)` in the `rely` function of the `vat`.

**Comment by kmbarry1** [comment]
The Pauses for those two actions will be very different though--DSR will be O(days) for economic responsiveness, `rely`/`deny` against the Vat will be O(months). Given that ES will take longer than a few days, in all likelihood, I think it's meaningful.

Also your argument that malicious governance can replace the Pot is irrelevant to choosing between the two solutions because they can do in the "disable `drip`" solution just as easily.

**Comment by gbalabasquer** [comment]
Yeah that is clear, it doesn't matter the type of protection we are setting in the `pot` if it can be eventually replaced. So I was not really meaning any difference between options regarding this problem.
However it is true that will be less problem with a longer pause for the `vat.rely/vat.deny` functions.

**Review by kmbarry1 — APPROVED** [review]
No objections here.

**Pull request merged**
