### PR TITLE
add messages to requires in frob

### PR DESCRIPTION
**Pull request by levity**
feel free to change the wording to suit you

### CODE REVIEW

**Comment by gbalabasquer** [comment]
@rainbreak I think we should do it now for the whole project. Were you thinking in some type of code styling for them?

**Comment by levity** [comment]
Looking forward to this landing in `vat.sol` now :)

**Comment by rainbreak** [comment]
@levity the reason for delaying here is trying to avoid ossifying prematurely, as there is potentially quite a lot of stuff to add checks for. Do you have an opinion on error codes vs messages? I'm leaning in favour of codes currently.

**Comment by levity** [comment]
I'm totally fine with codes; I just want to be able to tell, when I get a revert, which require is causing it. The first time I put them in myself locally I just called them "frob 1", "frob 2", etc. :)

**Pull request closed without merging**
