### PR TITLE
revert `file` calls if `what` is unrecognized

### PR DESCRIPTION
**Pull request by kmbarry1**
Addresses TOB-MCD-011. Will update k-dss as well.

### CODE REVIEW

**Comment by iamchrissmith** [comment]
I would have a slight preference to handle that separately because then we can point to separate PRs in response to the different issues.

**Comment by gbalabasquer** [comment]
Sounds good.

**Comment by kmbarry1** [comment]
@gbalabasquer yes, separate PR was my plan, for the exact reason that Chris mentions.

**Comment by asymmetric** [comment]
Is the issue public?

**Comment by kmbarry1** [comment]
@asymmetric  it will be public once the audit reports are released, but I can summarize quickly: this is just to prevent silent failures if one mistypes the `what` argument, not to mitigate any real vulnerability. This avoids issues like thinking a parameter has been changed when in fact it has not, and can speed up debugging cycles.

**Pull request merged**
