### PR TITLE
DaiMove and GemMove can access to the full rad value in vat

### PR DESCRIPTION
**Pull request by gbalabasquer**

### CODE REVIEW

**Comment by gbalabasquer** [comment]
@rainbreak proposed solution to being able to `move` `rad` values of `dai` and `gem`.
Honestly I'm not very convinced this is a good change. For `flip` feels good, but for `flap` and `flop` the difference between managing `dai` in `rad` and `gem` in `wad` doesn't feel right. I guess that is why the `move` objects took care of this conversion.

**Comment by gbalabasquer** [comment]
Closing this PR. I don't think we will `move` the whole `rad` value. In the case we want, we should make a new PR based on the latest changes.

**Comment by asymmetric** [comment]
Should we delete the branch?

**Comment by gbalabasquer** [comment]
Just did.

**Pull request closed without merging**
