### PR TITLE
vow, jug, pot: remove unneccessary restrictions on time variables

### PR DESCRIPTION
**Pull request by MrChico**
My humble opinion.

### CODE REVIEW

**Comment by asymmetric** [comment]
Why had 48 been chosen? 🕰

**Comment by MrChico** [comment]
2^48 = 281474976710656
Is equivalent to:
12/07/8921556 @ 10:44am (UTC)

Maybe during some less ambitious whiteboarding session it was decided that humanity would have transcended debt based interaction patterns at this point

**Comment by asymmetric** [comment]
Should've asked: why not 42?

**Comment by MrChico** [comment]
In auctions, two time variables are packed together with an address, fitting in one storage slot as. 
160+48+48=256
Rest of dss was adapted for consistency. But it introduces some annoying masking and stuff and doesn't really bring any benefit elsewhere, only more gas, bytecode and less aesthetics

**Pull request merged**
