### PR TITLE
Add tick to flop

### PR DESCRIPTION
**Pull request by iamchrissmith**
Adding a tick to flop. This allows for restarting the Flop auction if it reaches the `end` before receiving any `bid`s.

### CODE REVIEW

**Comment by andy8052** [comment]
Having `tic` and `tick` could be a little confusing, but I also can't think of another name for the function. Meme function & variable names have never been a forte of mine

**Comment by iamchrissmith** [comment]
This just mirrors the `tick` function in `Flip`, so I think it is best to be consistent (and I certainly don't have better ideas on the memes either :-) )

**Review by andy8052 — APPROVED** [review]

**Comment by gbalabasquer** [comment]
LGTM

**Comment by MrChico** [comment]
If one changes the size of the lot, from the slightly overzealous `uint(-1)` to, say a variable subject to `filing`, then the `tick` function could also bump up the lot at restart

**Comment by iamchrissmith** [comment]
> If one changes the size of the lot, from the slightly overzealous `uint(-1)` to, say a variable subject to `filing`, then the `tick` function could also bump up the lot at restart

So instead of starting an auction with `uint(-1)` on offer, start it with X MKR and then if no one bids, the system ups its offer to X * `beg` (for instance) and restarts the auction to see if people now want to bid?

**Comment by MrChico** [comment]
Essentially, yeah

**Comment by iamchrissmith** [comment]
@MrChico that makes sense, though I think it is too big for this PR.  I created another branch that addresses that potential change: https://github.com/makerdao/dss/pull/52
Lets discuss the impact/implementation there

**Pull request merged**
