### PR TITLE
Merge dsr

### PR DESCRIPTION
**Pull request by desaperados**
Move the dsr + commit history into dss:
```
github/makerdao/dsr/src/dsr.sol   -> src/pot.sol
github/makerdao/dsr/src/dsr.t.sol -> src/test/pot.t.sol
```

### CODE REVIEW

**Comment by asymmetric** [comment]
Should the copyright heading mention @gbalabasquer?

**Comment by desaperados** [comment]
I'm not a dsr contributor, just pulling the files over from the dsr repo.

**Comment by rainbreak** [comment]
@gbalabasquer I like this. How about you?

**Comment by gbalabasquer** [comment]
@rainbreak yeah 100%, let's get it merged.

**Pull request merged**
